[package]
name = "sum"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Oliveira olivmath@protonmail.com"]

[dependencies]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
