[server]
port = 7770
address = "0.0.0.0" 

[database]
db = "rocksdb"
application = "dev"

[reader]
cache_size = 1024
channel_size = 1024

[writer]
channel_size = 1024

[runner]
cache_size = 1024
channel_size = 100
